#!/usr/bin/python3
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def find_prime_factors(n):
    factors = []
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            if is_prime(i):
                factors.append(i)
            if is_prime(n // i):
                factors.append(n // i)
            break
    return factors
